# Generated by Django 3.1.7 on 2021-02-24 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210224_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
