# Generated by Django 3.1.7 on 2021-03-04 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_likes_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='products',
        ),
    ]
