# Generated by Django 3.1.7 on 2021-03-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210314_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliateproducttable',
            name='affiliate',
        ),
        migrations.RemoveField(
            model_name='affiliateproducttable',
            name='products',
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='photo',
            field=models.ImageField(upload_to='static/images/'),
        ),
        migrations.DeleteModel(
            name='Affiliate',
        ),
        migrations.DeleteModel(
            name='AffiliateProductTable',
        ),
    ]
